import type { Metadata } from "next";
import "./globals.css";
import { CartDrawer } from "@/components/CartDrawer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-satoshi  antialiased`}
      >
        {children}
        <CartDrawer/>
        <Toaster richColors position="top-center"/>
      </body>
    </html>
  );
}
